//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated manually to fix missing designer file.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroWard
{
    public partial class AdminPanel
    {
        /// <summary>lblAlert control</summary>
        protected global::System.Web.UI.WebControls.Label lblAlert;

        /// <summary>lblAdminName control</summary>
        protected global::System.Web.UI.WebControls.Label lblAdminName;

        /// <summary>lblDate control</summary>
        protected global::System.Web.UI.WebControls.Label lblDate;

        /// <summary>lblTime control</summary>
        protected global::System.Web.UI.WebControls.Label lblTime;

        /// <summary>lblTotalApps control</summary>
        protected global::System.Web.UI.WebControls.Label lblTotalApps;

        /// <summary>lblPendingApps control</summary>
        protected global::System.Web.UI.WebControls.Label lblPendingApps;

        /// <summary>lblApprovedToday control</summary>
        protected global::System.Web.UI.WebControls.Label lblApprovedToday;

        /// <summary>lblCitizens control</summary>
        protected global::System.Web.UI.WebControls.Label lblCitizens;

        /// <summary>lblPendingBadge control</summary>
        protected global::System.Web.UI.WebControls.Label lblPendingBadge;

        /// <summary>lblPageInfo control</summary>
        protected global::System.Web.UI.WebControls.Label lblPageInfo;

        /// <summary>txtSearch control</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>ddlStatusFilter control</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        /// <summary>ddlServiceFilter control</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlServiceFilter;

        /// <summary>gvApplications control</summary>
        protected global::System.Web.UI.WebControls.GridView gvApplications;

        /// <summary>btnPrev control</summary>
        protected global::System.Web.UI.WebControls.Button btnPrev;

        /// <summary>btnNext control</summary>
        protected global::System.Web.UI.WebControls.Button btnNext;

        /// <summary>btnLogout control</summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>rptNotices control</summary>
        protected global::System.Web.UI.WebControls.Repeater rptNotices;

        /// <summary>rptServiceStats control</summary>
        protected global::System.Web.UI.WebControls.Repeater rptServiceStats;

        /// <summary>hfActionAppID control</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActionAppID;

        /// <summary>hfCurrentPage control</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentPage;
    }
}
