//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroWard.CitizenshipRegistration
{
    public partial class CitizenshipNew
    {
        /// <summary>txtNameNep control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNameNep;

        /// <summary>txtNameEng control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtNameEng;

        /// <summary>txtDOBBS control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDOBBS;

        /// <summary>txtDOBAD control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDOBAD;

        /// <summary>ddlGender control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;

        /// <summary>ddlBloodGroup control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBloodGroup;

        /// <summary>ddlDistrict control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlDistrict;

        /// <summary>txtMunicipality control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMunicipality;

        /// <summary>txtWardNo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtWardNo;

        /// <summary>txtTole control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTole;

        /// <summary>txtFatherNameNep control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFatherNameNep;

        /// <summary>txtFatherNameEng control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFatherNameEng;

        /// <summary>ddlFatherAlive control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlFatherAlive;

        /// <summary>txtFatherCitizenshipNo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFatherCitizenshipNo;

        /// <summary>chkSelfDeclaration control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkSelfDeclaration;

        /// <summary>txtMotherNameNep control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotherNameNep;

        /// <summary>txtMotherNameEng control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotherNameEng;

        /// <summary>ddlMotherAlive control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlMotherAlive;

        /// <summary>txtMotherCitizenshipNo control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotherCitizenshipNo;

        /// <summary>txtGrandfatherNameNep control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtGrandfatherNameNep;

        /// <summary>txtGrandfatherNameEng control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtGrandfatherNameEng;

        /// <summary>txtGrandmotherNameNep control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtGrandmotherNameNep;

        /// <summary>txtGrandmotherNameEng control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtGrandmotherNameEng;

        /// <summary>chkParentDeceased control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkParentDeceased;

        /// <summary>chkMarried control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkMarried;

        /// <summary>chkMigrated control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkMigrated;

        /// <summary>fileDeathCert control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileDeathCert;

        /// <summary>txtHusbandName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtHusbandName;

        /// <summary>fileMarriageCert control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileMarriageCert;

        /// <summary>fileMigration control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileMigration;

        /// <summary>filePhoto control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload filePhoto;

        /// <summary>fileBirth control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileBirth;

        /// <summary>fileFatherCitizenship control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileFatherCitizenship;

        /// <summary>fileMotherCitizenship control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileMotherCitizenship;

        /// <summary>fileEducation control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fileEducation;

        /// <summary>btnDraft control.</summary>
        protected global::System.Web.UI.WebControls.Button btnDraft;

        /// <summary>btnSubmit control.</summary>
        protected global::System.Web.UI.WebControls.Button btnSubmit;
    }
}
