//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HamroWard
{
    public partial class NewsNotices
    {
        /// <summary>
        /// rptNotices control — Repeater that renders the news/notice cards.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptNotices;

        /// <summary>
        /// pnlEmpty control — Shown when there are no records in the database.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// pnlViewToggle control — Wraps the View All / View Less button.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlViewToggle;
    }
}
